services:
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb:3306 # Name and port of the database container

    restart: always
    networks:
      - inception
  
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception

networks:
  inception:
    driver: bridge