services:
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST_NAME=mariadb # Name and port of the database container
      - MYSQL_HOST_PORT=3306    # Port of the database container
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    environment:
      - PAGE_DOMAIN=${PAGE_DOMAIN}
      - CERTS_PATH=${CERTS_PATH}
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: volumes/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: volumes/mariadb

networks:
  inception:
    driver: bridge